### ISSUE TITLE
Naval warfare rebalance 

### ISSUE THREAD

**Issue by ArchMikeX** [ma44/NCRvL-OWB#7]
Increase overall health of all ship hulls and decrease the damage output of all their weapon modules. Make hulls of intermediate and sophisticated tech more enticing in terms of health and armor. With these changes naval battles will last longer and players will be able to actually see what's happening in them. They might even be able to preserve considerable part of their fleets if they choose to retreat from a naval battle.

Make triremes and canoes undesirable for players to use by restricting them to have just one or a couple weapon module slots.

Give navy players a naval carrier ship design opened. Naval carriers can be fun to use for landings deep inside enemy territory or to simply have more epic naval battles.

Significantly increase the range of all ships. Make it so that players will be able to achieve enough range to execute landing from Mexico to Oregon and from California to Texas. 

Add flying harbors technology so that naval invasions would not simply die in a week from the lack of supply.

**Comment by InsertMemeHere12192002** [comment]
Addressed.
